data_prep:
  dataset_name: "Iris Species Classification"
  feature_columns: 
    - "SepalLengthCm"
    - "SepalWidthCm" 
    - "PetalLengthCm"
    - "PetalWidthCm"
  target_column: "Species"
  drop_columns:
    - "Id"
  
feature_prep:
  apply_scaling: true
  scaling_method: "StandardScaler"
  apply_feature_engineering: true
  engineered_features:
    - "SepalRatio"     # SepalLengthCm / SepalWidthCm
    - "PetalRatio"     # PetalLengthCm / PetalWidthCm
    - "SepalArea"      # SepalLengthCm * SepalWidthCm
    - "PetalArea"      # PetalLengthCm * PetalWidthCm
    - "TotalLength"    # SepalLengthCm + PetalLengthCm
    - "TotalWidth"     # SepalWidthCm + PetalWidthCm

model_evaluation:
  cv_folds: 5
  cv_shuffle: true
  random_state: 42
  primary_metric: "macro_averaged_auc"
  secondary_metrics:
    - "accuracy"
    - "precision_macro"
    - "recall_macro"
    - "f1_macro"

model:
  model_type: "RandomForestClassifier"
  model_params:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
